name: 'Terraform CI/CD'

on:
  push:
    branches:
      - develop-deploy # Se activa solo con pushes a la rama 'main'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT_ID }} # Define una variable de entorno

    steps:
      # 1. Clona el repositorio para que el workflow tenga acceso al código
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Autentica con GCP usando la clave de la cuenta de servicio
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_TERRAFORM }}

      # 3. Instala la versión de Terraform que necesites
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0 # Puedes cambiar la versión

      # 4. Inicializa Terraform (descarga providers y configura el backend)
      - name: Terraform Init
        id: init
        run: terraform init

      # 5. Genera el plan de ejecución para ver los cambios
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color

      # 6. Aplica los cambios SOLO si el push es a la rama 'main'
      - name: Terraform Apply
        if: github.ref == 'refs/heads/develop-deploy'
        run: terraform apply -auto-approve -input=false